### ISSUE TITLE
"The server returned an invalid response to our download request." when downloading via extension under VPN extension

### ISSUE THREAD

**Issue by Gersonzao** [erickutcher/httpdownloader#223]
Persepolis works fine, but is unmaintained. This specifically happens with Ivacy VPN (other VPNs are fine), so I'm not sure whether it's a problem with HTTP Downloader or with the virtual private network... I think I'll just keep using Persepolis until I find a maintained download manager that works
Application: 1.0.5 Dark Mode (64-bit)
Extension: 1.0.2.3
Web browser: Firefox ESR 102.12 (fresh profile attempted)
Operating system: Windows 10 version 2004

![image](https://github.com/erickutcher/httpdownloader/assets/85644671/c020a9f4-31bd-4057-bf49-53eca9a91160)

**Comment by erickutcher** [comment]
By default the extension communicates to the program by sending a request through the localhost. Try changing the server to http://127.0.0.1:80/

**Comment by erickutcher** [comment]
I updated the Firefox extension because of a bug with the server credentials. They weren't being passed correctly when using the Save As... context menus. If you set HTTP Downloader to use a username and password for its server, then it should be fixed now. Just update the extension to the latest version (1.0.2.4).

**Comment by Gersonzao** [comment]
> By default the extension communicates to the program by sending a request through the localhost. Try changing the server to http://127.0.0.1:80/

I assume you mean to change the extension's configured server URI; I have tried changing it in the extension, in HTTP Downloader and then in both, but it still doesn't work.
> I updated the Firefox extension because of a bug with the server credentials. They weren't being passed correctly when using the Save As... context menus. If you set HTTP Downloader to use a username and password for its server, then it should be fixed now. Just update the extension to the latest version (1.0.2.4).

I did not use passwords for the server.

I do not use Ivacy VPN anymore and I'm pretty sure this issue doesn't affect many people so feel free to close it.
