### ISSUE TITLE
Site Manager didn't work

### ISSUE THREAD

**Issue by ZmdnaHF0ZmFqYXZ0O** [erickutcher/httpdownloader#305]
Dear developer, 
I set these sites: https://*.github.com and https://*.githubusercontent.com in Site manager, and these URL will use a proxy to download, but it didn't work, when I download any files from github ( the files URL like https://github.com/DEVELOPER_NAME/PROJECT_NAME/releases/download/VERSION/FILENAMES.zip, and the files' real URL are https://objects.githubusercontent.com/github-xxxxxx ), it always direct download without the proxy, is it a issue? 
Thanks!
![image](https://github.com/user-attachments/assets/73d76cbb-e13e-470c-ae17-0c6a347491fe)

**Comment by erickutcher** [comment]
I think there might be a bug with the wildcard value.

If you use `https://github.com` and `https://objects.githubusercontent.com` instead then it should work.

I'll look into this.

**Comment by erickutcher** [comment]
Turns out it had to do with the URL redirection. It wasn't applying the Site Manager values to the redirected URL. I think I'll add an option to apply the same proxy values for redirected URLs if the initial URL has a proxy set. But for now, this bug has been fixed.

**Comment by ZmdnaHF0ZmFqYXZ0O** [comment]
Thanks for your reply.

**Comment by erickutcher** [comment]
A new version is up that should have this fixed.

**Comment by ZmdnaHF0ZmFqYXZ0O** [comment]
Hi, I tried the new verion, but *.github.com still don't include github.com, thanks.

**Comment by erickutcher** [comment]
You'll need two separate entries. The wildcard only targets subdomains. That's by design, but maybe I'll have it include the main domain in a later version.
